AWS S3 em Python
ButecoOpenSource/butecoopensource.github.io pull request #11
Opened 2020-05-09 09:23 UTC by jaswdr

2020-05-09 11:23 UTC, alexandrevicenzi requested changes

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +tagline: "Diversas aplicações precisam em algum momento armazenar arquivos, seja para backup, CDN ou outros. Um dos serviços mais utilizados para armazenamento de arquivos é o AWS S3. Veja neste arti
tagline deveria ser um pouco mais curta e sem . no fim

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +date: 2020-05-08 12:00:00
data deve ser alguma futura, com o dia pretendido pra soltar no ar

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +> Diversas aplicações precisam em algum momento armazenar arquivos, seja para backup, CDN ou outros. Um dos serviços mais utilizados para armazenamento de arquivos é o AWS S3. Veja neste artigo como
precisa disso aqui? ja ta no excerpt

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +## Criando usuario de acesso ao S3
Usuário

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +> Diversas aplicações precisam em algum momento armazenar arquivos, seja para backup, CDN ou outros. Um dos serviços mais utilizados para armazenamento de arquivos é o AWS S3. Veja neste artigo como
poderia começar com uma introducao ao S3, o que é, comko funciona e tal. algo bem alto nivel, e falar que nao tem so o S3 da AWS, mas como por exeplo, Ceph suporta :) ou até falar do Minio.

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +> Diversas aplicações precisam em algum momento armazenar arquivos, seja para backup, CDN ou outros. Um dos serviços mais utilizados para armazenamento de arquivos é o AWS S3. Veja neste artigo como
outra coisa, como é aws seria legal falar do free tier ou falar dos custos

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Clique em "Next: Permissions" para adicionarmos as permissões ao nosso usuário. Nesse exemplo vamos adicionar as permissões diretamente ao usuário, para isso clique na tab "Attach existing policies d
irá e não ira

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Se tudo ocorrer como esperado você vera uma pagina com os dados de "Access key ID" e "Secret access key", salve estes dois valores pois iremos usar a seguir.
verá uma página

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Se tudo ocorrer como esperado você vera uma pagina com os dados de "Access key ID" e "Secret access key", salve estes dois valores pois iremos usar a seguir.
e se der erro? o que acontece xD

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +pip install boto3
pip3 seria o certo, pip instala no python2 geralmente, a algumas distros nem tem python2 e pip

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Uma vez instalado precisamos criar um cliente usando as credencias do usuário que acabamos de criar.
Uma vez instalado, precisamos...

Credenciais e nao credencias

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +    aws_access_key_id='seu_access_key_id',
da onde sai a key? nao ta escrito

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Usando a função `create_bucket` podemos criar um novo bucket, no exemplo acima estamos criando um bucket com acesso `private`, ou seja, apenas nosso usuario tera acesso ao bucket. Alem disso estamos
. No exemplo acima...

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Usando a função `create_bucket` podemos criar um novo bucket, no exemplo acima estamos criando um bucket com acesso `private`, ou seja, apenas nosso usuario tera acesso ao bucket. Alem disso estamos
usuario ta sem acento

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Usando a função `create_bucket` podemos criar um novo bucket, no exemplo acima estamos criando um bucket com acesso `private`, ou seja, apenas nosso usuario tera acesso ao bucket. Alem disso estamos
alem tem acento e vai virgula.

além disso, estamos...

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Usando a função `create_bucket` podemos criar um novo bucket, no exemplo acima estamos criando um bucket com acesso `private`, ou seja, apenas nosso usuario tera acesso ao bucket. Alem disso estamos
latência não precisa de plural

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Usando a função `create_bucket` podemos criar um novo bucket, no exemplo acima estamos criando um bucket com acesso `private`, ou seja, apenas nosso usuario tera acesso ao bucket. Alem disso estamos
nesse caso, é importante

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Usando a função `create_bucket` podemos criar um novo bucket, no exemplo acima estamos criando um bucket com acesso `private`, ou seja, apenas nosso usuario tera acesso ao bucket. Alem disso estamos
for ta errado

o custo por GB é menor

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Usando a função `create_bucket` podemos criar um novo bucket, no exemplo acima estamos criando um bucket com acesso `private`, ou seja, apenas nosso usuario tera acesso ao bucket. Alem disso estamos
. Veja a tabela...

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Usando a função `create_bucket` podemos criar um novo bucket, no exemplo acima estamos criando um bucket com acesso `private`, ou seja, apenas nosso usuario tera acesso ao bucket. Alem disso estamos
ta faltando a tabela eu acho :thinking:

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Criado nosso bucket podemos acessar o console da nossa conta na AWS e ir área do S3 na região que criamos o bucket, podemos ver que o bucket foi criado com sucesso.
Criado nosso bucket, podemos ...

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Criado nosso bucket podemos acessar o console da nossa conta na AWS e ir área do S3 na região que criamos o bucket, podemos ver que o bucket foi criado com sucesso.
nao faz sentido:

e ir área do S3 na região

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Agora que confirmamos que nosso bucket foi criado vamos fazer o primeiro upload, mas antes vamos criar um arquivo de texto com um conteúdo qualquer.
Agora que confirmamos que nosso bucket foi criado, vamos...

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +f = open("hello-s3.txt", "w+")
```py
with open() as f:
  f.write()
```
nao precisa dar close dai xD

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +O metodo `upload_file` precisa de 3 parâmetros, o primeiro é o caminho para o arquivo que queremos fazer upload, o segundo é o nome do bucket e o ultimo é o nome da chave do arquivo no S3. Acessando
Último tem acento

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Para isso usamos o método `download_file` que precisa de 3 parâmetros, o primeiro é o nome do bucket, o segundo é a chave do objeto que queremos fazer o download, no nosso caso "hello-s3", e por últi
Executando com sucesso o código acima, é...

2020-05-09 11:23 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Até a próxima
falta um ponto final ou algo

2020-05-11 20:01 UTC, jaswdr commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +> Diversas aplicações precisam em algum momento armazenar arquivos, seja para backup, CDN ou outros. Um dos serviços mais utilizados para armazenamento de arquivos é o AWS S3. Veja neste artigo como
a intençāo é focar no S3 mesmo, vou remover o trecho e adicionar uma introduçāo rápida.

2020-05-11 20:05 UTC, jaswdr commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Se tudo ocorrer como esperado você vera uma pagina com os dados de "Access key ID" e "Secret access key", salve estes dois valores pois iremos usar a seguir.
se der erro só escrevendo um comentário xD

2020-05-11 20:11 UTC, jaswdr commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +    aws_access_key_id='seu_access_key_id',
na primeira parte falo para salvar o access key

2020-05-11 20:18 UTC, jaswdr commented
@prscheduler 15/05/2020T12:00

2020-05-11 21:36 UTC, alexandrevicenzi requested changes

2020-05-11 21:36 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +Gravando o conteúdo "Ola, S3!" num arquivo `hello-s3.txt` podemos fazer o upload dele para o S3 da seguinte maneira.
faltou acento no Olá, ta certo? o content tem acento

2020-05-11 21:36 UTC, alexandrevicenzi commented on _posts/2020-05-15-usando-aws-s3-em-python.md
> +# ['\n', 'Ola, S3!\n']
sem acento aqui tambem

2020-05-12 11:16 UTC, alexandrevicenzi approved these changes

2020-05-15 12:00 UTC, merged