Review Ubuntu 20.04
ButecoOpenSource/butecoopensource.github.io pull request #13
Opened 2020-05-14 15:21 UTC by alexandrevicenzi

2020-05-14 17:13 UTC, alexandrevicenzi commented
@prscheduler 20/05/2020T12:00

2020-05-15 08:10 UTC, jaswdr requested changes

2020-05-15 08:10 UTC, jaswdr commented on _posts/2020-05-20-ubuntu-20-04.md
> +A versão 20.04 está puxando mais para instalar pacotes via Snap, alguns até sumiram do Apt, ou seja, só instala o pacote do Snap.
"focando" no lugar de "puxando"?

2020-05-17 09:20 UTC, jaswdr approved these changes

2020-05-20 12:00 UTC, merged