Entendendo carros autônomos
ButecoOpenSource/butecoopensource.github.io pull request #16
Opened 2020-05-25 18:03 UTC by alexandrevicenzi

2020-05-25 18:04 UTC, alexandrevicenzi commented
@prscheduler 28/05/2020T12:00

2020-05-26 01:37 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Um carro autônomo é um carro capaz de identificar o ambiente ao seu redor e trafegar com segurança com nenhuma ou pouca iteração humana.
trafegar em segurança fica melhor eu acho

2020-05-26 01:39 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Um carro autônomo combina uma variedade de sensores para perceber o ambiente ao seu redor, dentre eles, podemos citar o uso de GPS, Lidar, Radar, Sonar e câmeras.
Combinam uma variedade... (acho que fica repetitivo começar com "um carro autonomo" de novo)

2020-05-26 01:41 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Um carro autônomo não é feito só de sensores, na verdade, sensores são apenas uma parte, ainda precisamos de um sistema de controle, como um sistema operacional, capaz de interpretar os dados coletad
(Um carro autonomo) de novo, repetitivo

2020-05-26 01:42 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Os freios de emergência ou EBA (Emergency brake assist) populares em caminhões, é um sistema semi autônomo capaz de parar um veículo em situações de risco onde o motorista não teve um tempo de respos
Poderia ser unificado com o paragrafo anterior

2020-05-26 01:44 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Os carros da Tesla, tecnicamente possuem todo o hardware necessário para que o carro seja totalmente autônomo, onde ele seja capaz de ir de um ponto a outro sem interação humana, curta ou longa distâ
Os carros da Tesla tecnicamente (remover primeira virgula)

2020-05-26 01:45 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Podemos dizer que o desafio DARPA foi um dos grande propulsores em relação a veículos autônomos.
Poderia ser unificado com o primeiro paragrado sobre a DARPA

2020-05-26 01:46 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +* Nível 0 - O veículo é controlado por humanos, o sistema autônomo emitir alertas, mas ele não possui controle sobre o veículo.
o sistema autônomo emite alertas mas não possui controle sobre o veículo.

2020-05-26 01:48 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +A Tesla é apenas uma das empresas fazendo pesquisas e testes, talvez a mais conhecida, pois os carros estão a venda e é possível encontrar facilmente carros Tesla nas ruas dos Estados Unidos.
.Talvez seja a mais conhecida pois...

2020-05-26 01:50 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +O [Uber](https://www.uber.com/us/en/atg/technology/){:target="_blank"} é outra com pesquisas, e ainda podemos citar que todas a grandes fabricantes de veículos possuem algum programa similar.
Poderia ser mais genérico.

2020-05-26 01:50 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Provavelmente você deve pensar que a NVDIA faz apenas GPU certo? Errado.
Juntar com o paragrafo abaixo

2020-05-26 01:51 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +No atual momento estamos no nível 2, nesse nível já podemos assegurar de que muitas vidas já foram salvas. No nível 4, a tendência é proporcionar uma segurança ainda maior, reduzindo os acidentes fat
Melhorar frase sobre nivel 2. Talvez adicionar uma fonte sobre a diminuição no número de mortes

2020-05-26 01:54 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +O nível 2 já está em circulação, já existem pesquisas e projetos em todos os níveis, e é uma questão de poucos anos até termos veículos nível 4 em circulação.
Melhorar a frase. "Carros com nível 2 de automação já estão em circulação... e =é uma questão de poucos anos até termos veículos circulando com nível 4"

2020-05-26 01:54 UTC, marcosps commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Certamente ainda é um tema um tanto quanto polêmico, ainda necessitamos nos adaptar a ideia de carros sem motoristas, mas as pessoas estão começando a perceber as vantagens, é uma questão de tempo at
Melhorar as frases

2020-05-26 11:52 UTC, alexandrevicenzi commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Os freios de emergência ou EBA (Emergency brake assist) populares em caminhões, é um sistema semi autônomo capaz de parar um veículo em situações de risco onde o motorista não teve um tempo de respos
sei nao, fica estranho

2020-05-26 11:54 UTC, alexandrevicenzi commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Podemos dizer que o desafio DARPA foi um dos grande propulsores em relação a veículos autônomos.
mudei, mas nao para o 1o

2020-05-26 12:25 UTC, jaswdr requested changes

2020-05-26 12:25 UTC, jaswdr commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +No exemplo acima é possível observar o Tesla Autopilot em ação, porém ainda são necessárias muitas horas e quilômetros de estrada para que chegamos a um ponto onde seja possível confiar nesses sistem
"para que chegamos" -> "para chegarmos" ?

2020-05-26 12:25 UTC, jaswdr commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +A primeira competição foi em 2004, porém nenhum dos veículos autônomos conseguir chegar ao final da competição.
"veículos autônomos conseguir chegar" -> "veículos autônomos conseguiu chegar"

2020-05-26 12:25 UTC, jaswdr commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +* Nível 0 - O sistema autônomo emitir alertas, mas ele não possui controle sobre o veículo.
"emitir" -> "emite"?

2020-05-26 12:25 UTC, jaswdr commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Com uma frota totalmente autônoma, pode ser que você não precise mais ter um carro, você pode abrir uma App, chamar um carro e ir para aonde quiser. Consequentemente você terá menos gastos e teremos
"uma App" -> "um App"?

2020-05-26 12:40 UTC, alexandrevicenzi commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Com uma frota totalmente autônoma, pode ser que você não precise mais ter um carro, você pode abrir uma App, chamar um carro e ir para aonde quiser. Consequentemente você terá menos gastos e teremos
o corretor sugere que App é feminino

2020-05-26 12:41 UTC, alexandrevicenzi commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Com uma frota totalmente autônoma, pode ser que você não precise mais ter um carro, você pode abrir uma App, chamar um carro e ir para aonde quiser. Consequentemente você terá menos gastos e teremos
https://www.dicio.com.br/app/

2020-05-26 12:43 UTC, jaswdr commented on _posts/2020-05-28-entendendo-carros-autonomos.md
> +Com uma frota totalmente autônoma, pode ser que você não precise mais ter um carro, você pode abrir uma App, chamar um carro e ir para aonde quiser. Consequentemente você terá menos gastos e teremos
👍

2020-05-26 20:03 UTC, jaswdr approved these changes

2020-05-28 12:00 UTC, merged