Conhecendo o Btrfs
ButecoOpenSource/butecoopensource.github.io pull request #22
Opened 2020-07-30 21:14 UTC by alexandrevicenzi

2020-07-30 22:01 UTC, jaswdr requested changes

2020-07-30 22:01 UTC, jaswdr commented on _posts/2020-07-31-conhecendo-o-btrfs.md
> +Imagine um subvolume como se fosse uma partição de disco, mas totalmente gerenciado pelo mesmo sistema de arquivos, contendo sistemas de arquivo independentes e podendo até mesmo utilizar quota para
... arquiv`o` .. por arquivos?

2020-07-30 22:01 UTC, jaswdr commented on _posts/2020-07-31-conhecendo-o-btrfs.md
> +Distribuições Linux como o openSUSE se utilizam deste recurso para um subvolume na raiz do sistema, ou `/`, e dentro deste criar outros subvolumes para diretórios importantes como `/var`, `/home`, `/
... deste recurso para um subvolume ... => deste recurso para criar um subvolume ?

2020-07-30 22:01 UTC, jaswdr commented on _posts/2020-07-31-conhecendo-o-btrfs.md
> +Um snapshot não passa de um subvolume com um conteúdo inicial, ao contrário de um subvolume comum que não tem nenhum conteúdo após sua criação. É utilizado para criar uma imagem, um ponto no tempo de
... sua criação. É utilizado para criar ... => sua criação. Um Snapshot é utilizado para criar

2020-07-30 22:01 UTC, jaswdr commented on _posts/2020-07-31-conhecendo-o-btrfs.md
> +Por padrão, Btrfs utilizar RAID 1 para metadados, mesmo que o sistema estiver utilizando somente um disco. Desta forma se por acaso uma cópia do metadata sendo acessado estiver corrompida, o Btrfs po
utilizar => utiliza

2020-07-30 22:46 UTC, alexandrevicenzi commented
@prscheduler 21/07/2020T12:00

2020-07-30 22:46 UTC, alexandrevicenzi commented
@prscheduler 31/07/2020T12:00

2020-07-31 08:43 UTC, jaswdr approved these changes

2020-07-31 12:00 UTC, merged