Começando com SQLAlchemy
ButecoOpenSource/butecoopensource.github.io pull request #4
Opened 2020-04-04 21:32 UTC by jaswdr

2020-04-20 08:35 UTC, alexandrevicenzi requested changes
Também é necessario ajustar o header, alterando layout, author e demais.

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +​	Diversas aplicaçōes escritas na linguagem Python precisam armazenar dados relacionais, usando bancos de dados como PostgreSQL, MySQL, Oracle e outros, o projeto `sqlalchemy` visa facilitar a conexã
escritas em Python fica melhor

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +​	Diversas aplicaçōes escritas na linguagem Python precisam armazenar dados relacionais, usando bancos de dados como PostgreSQL, MySQL, Oracle e outros, o projeto `sqlalchemy` visa facilitar a conexã
. O projeto ...

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +​	Diversas aplicaçōes escritas na linguagem Python precisam armazenar dados relacionais, usando bancos de dados como PostgreSQL, MySQL, Oracle e outros, o projeto `sqlalchemy` visa facilitar a conexã
. nova lina Veja a seguir como...

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +Após finalizar o download e instalação você verificar a instalação pelo python, executando:
você pode verificar....

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +No exemplo acima, estamos criando uma instância de `Engine` com o `sqlite`, caso você queira conectar com outro banco, veja a [documentação](https://docs.sqlalchemy.org/en/13/dialects/index.html).
veja a documentacao (en Inglês) para mais detalhes

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +Uma vez que temos nossa engine podemos começar a criar nossas sessões.
Tem mais de uma sessao? Eu acho que nao.

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +session.execute('INSERT INTO "users" (id, name, email) VALUES '
Usa " que ai nao precisa dos \ nas string, fica mais clean.

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +result = session.execute('SELECT * FROM users')
Tem exemplo de dict row? set é meio basicão.

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +Como pode-se ver no exemplo, quando se utiliza o ORM do sqlalchemy os atributos da classe são inicializados com instâncias de `sqlalchemy.Column`, no caso estamos criando colunas de "id", "name" e "e
Além disso, o ...

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +Uma vez montado nosso primeiro modelo de usuário podemos gerar toda a estrutura do banco usando um método utilitário da classe `Base` que criamos.
Uma ver montado, ...

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +Caso o comando acima execute com sucesso é esperado termos agora uma tabela `users` representado pela nossa classe, com isso podemos da mesma forma que anteriormente adicionar alguns usuários.
Caso o comando acima seja executado com sucesso, é esperado termos agora uma tabela `users`... parece-me melhor

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +Perceba a forma como buscamos os usuários com o método `query` passando como parâmetro a entidade que queremos, no caso `User`, a forma acima irá buscar todos os usuários sem filtro algum, podemos fi
. nova linha Podemos filtrar...... com o metodo filter:

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +Dessa forma conseguimos facilmente alterar nosso banco, podemos também excluir os registros com o método `delete()`.
. nova linha Podemos ...

2020-04-20 08:35 UTC, alexandrevicenzi commented on _posts/2020-04-04-comecando-com-sqlalchemy.md
> +O `sqlalchemy` possuí um conjunto de opções que tanto facilitam trabalhar com bancos relacionais como dão flexibilidade de executar comandos SQL ou criar modelos utilizando o pacote ORM. Você já util
. nova linha Voce já utilizou....

? Deixe um comentário.

2020-04-21 18:42 UTC, jaswdr commented
@alexandrevicenzi feito correções

2020-04-21 19:58 UTC, alexandrevicenzi commented
Por algum motivo tem 2 arquivos MD, e a imagem do PR não é usada.

2020-04-21 20:16 UTC, alexandrevicenzi approved these changes

2020-04-22 18:39 UTC, merged